### ISSUE TITLE
Is this dead?

### ISSUE THREAD

**Issue by Suya1671** [zorbyte/Socus#23]
Title says it all. Last commit was on 25th Jan this year.

**Comment by TTtie** [comment]
Hi there!
Indeed, others have already made (potentially better) working libraries for interfacing with Discord's API using Deno. And yes, indeed, no work on the core of Denocord is being done right now (at the time of writing this comment).

Unfortunately, a large portion of my interest in Deno as a whole has fallen off and I myself don't even know whether the library still works with the latest Deno versions as it currently is. (the probability of it not working as expected increases if using `zlib-stream` compression with native plugin loading enabled, as it is very likely incompatible with the current extension ABI, although a WASM fallback should exist for that)

After all, the way it (especially the REST part) turned out wasn't in my opinion great either - at this point it would be great starting off from zero again...

One day, I might get the mood and energy to get back to working on it, but who knows? Only time will tell. Until then, this library and the modules associated with it should be considered (at least) unmaintained, available to anyone as it currently is. 

Thanks for understanding.

**Comment by Suya1671** [comment]
ok. Someone else is making a library with the same name so thats why Im asking
